name: Continious integration

on: [push]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300
      - run: dotnet build Phone.App
      - run: dotnet test Phone.Tests